package actions

import (
	"github.com/edTheGuy00/slack_clone_backend/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (TeamMember)
// DB Table: Plural (team_members)
// Resource: Plural (TeamMembers)
// Path: Plural (/team_members)
// View Template Folder: Plural (/templates/team_members/)

// TeamMembersResource is the resource for the TeamMember model
type TeamMembersResource struct {
	buffalo.Resource
}

// List gets all TeamMembers. This function is mapped to the path
// GET /team_members
func (v TeamMembersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	teamMembers := &models.TeamMembers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all TeamMembers from the DB
	if err := q.All(teamMembers); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, teamMembers))
}

// Show gets the data for one TeamMember. This function is mapped to
// the path GET /team_members/{team_member_id}
func (v TeamMembersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty TeamMember
	teamMember := &models.TeamMember{}

	// To find the TeamMember the parameter team_member_id is used.
	if err := tx.Find(teamMember, c.Param("team_member_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, teamMember))
}

// New renders the form for creating a new TeamMember.
// This function is mapped to the path GET /team_members/new
func (v TeamMembersResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.TeamMember{}))
}

// Create adds a TeamMember to the DB. This function is mapped to the
// path POST /team_members
func (v TeamMembersResource) Create(c buffalo.Context) error {
	// Allocate an empty TeamMember
	teamMember := &models.TeamMember{}

	// Bind teamMember to the html form elements
	if err := c.Bind(teamMember); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(teamMember)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, teamMember))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "TeamMember was created successfully")

	// and redirect to the team_members index page
	return c.Render(201, r.Auto(c, teamMember))
}

// Edit renders a edit form for a TeamMember. This function is
// mapped to the path GET /team_members/{team_member_id}/edit
func (v TeamMembersResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty TeamMember
	teamMember := &models.TeamMember{}

	if err := tx.Find(teamMember, c.Param("team_member_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, teamMember))
}

// Update changes a TeamMember in the DB. This function is mapped to
// the path PUT /team_members/{team_member_id}
func (v TeamMembersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty TeamMember
	teamMember := &models.TeamMember{}

	if err := tx.Find(teamMember, c.Param("team_member_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind TeamMember to the html form elements
	if err := c.Bind(teamMember); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(teamMember)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, teamMember))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "TeamMember was updated successfully")

	// and redirect to the team_members index page
	return c.Render(200, r.Auto(c, teamMember))
}

// Destroy deletes a TeamMember from the DB. This function is mapped
// to the path DELETE /team_members/{team_member_id}
func (v TeamMembersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty TeamMember
	teamMember := &models.TeamMember{}

	// To find the TeamMember the parameter team_member_id is used.
	if err := tx.Find(teamMember, c.Param("team_member_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(teamMember); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "TeamMember was destroyed successfully")

	// Redirect to the team_members index page
	return c.Render(200, r.Auto(c, teamMember))
}
